version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pa
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - db
  app: 
    build: ./app/
    container_name: app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: database
      DB_USER: user
      DB_PASSWORD: pa
    networks:
      - db
networks:
  db:
    driver: bridge
    
volumes:
  mysql_data:
    driver: local
  mysql_config:
    driver: local
