FROM mysql:5.6

# set root password
ENV MYSQL_ROOT_PASSWORD=pass

# create database and table
RUN chmod 744 /docker-entrypoint-initdb.d/
COPY init.sql /docker-entrypoint-initdb.d/

# add a new user
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=puser

EXPOSE 3306
